import type { Merchant, MerchantProfile } from '../schemas'

const CREATED = '2026-08-01T02:00:00.000Z'

export const SEED_MERCHANTS: Merchant[] = [
  {
    id: 'sherpa-computers',
    name: 'Sherpa Computers',
    slug: 'sherpa-computers',
    sizeType: 'sme',
    category: 'laptops',
    websiteUrl: 'https://sherpa-computers-demo.myshopify.com',
    platform: 'shopify',
    commercePlatform: 'shopify',
    currency: 'SGD',
    agentId: 'merchant_sherpa_computers_8H3K2',
    visaMode: 'simulated',
    networkEnabled: true,
    storefrontEnabled: true,
    logoHue: 220, // Wisteria Blue
    createdAt: CREATED,
  },
  {
    id: 'bizgram',
    name: 'Bizgram',
    slug: 'bizgram',
    sizeType: 'mid',
    category: 'laptops',
    websiteUrl: 'https://bizgram-demo.example.com',
    platform: 'custom',
    commercePlatform: 'custom',
    currency: 'SGD',
    agentId: 'merchant_bizgram_QR47P',
    visaMode: 'simulated',
    networkEnabled: true,
    storefrontEnabled: true,
    logoHue: 178, // Strong Cyan
    createdAt: CREATED,
  },
  {
    id: 'challenger',
    name: 'Challenger',
    slug: 'challenger',
    sizeType: 'chain',
    category: 'laptops',
    websiteUrl: 'https://challenger-demo.example.com',
    platform: 'custom',
    commercePlatform: 'custom',
    currency: 'SGD',
    agentId: 'merchant_challenger_5MW9D',
    visaMode: 'simulated',
    networkEnabled: true,
    storefrontEnabled: true,
    logoHue: 340, // Wild Strawberry
    createdAt: CREATED,
  },
]

export const SEED_PROFILES: MerchantProfile[] = [
  {
    merchantId: 'sherpa-computers',
    primaryObjective: 'inventory_turnover',
    secondaryObjective: 'margin',
    maxDiscountPct: 8,
    minMarginPct: 6,
    bundleAllowance: 55,
    standardWarrantyYears: 1,
    maxWarrantyYears: 2,
    standardDeliveryDays: 2,
    inventoryPriorities: ['last_gen', 'overstock'],
    brandTone: 'Direct, no-nonsense, price-first. Sounds like a shop owner who knows the stock.',
    salesRules: [
      {
        id: 'tan-rule-1',
        kind: 'min_spec_for_workload',
        text: 'Engineering and CAD customers must be offered at least 16 GB RAM.',
        params: { workloads: ['cad', 'engineering', '3d', 'solidworks'], minRamGb: 16 },
        approved: true,
        source: 'seed',
      },
      {
        id: 'tan-rule-2',
        kind: 'prefer_upgrade_over_discount',
        text: 'Prefer bundling an accessory over a cash discount above 4%.',
        params: { discountThresholdPct: 4 },
        approved: true,
        source: 'seed',
      },
      {
        id: 'tan-rule-3',
        kind: 'prioritize_tag',
        text: 'Move previous-generation stock first when customer fit stays strong.',
        params: { tags: ['last_gen'] },
        approved: true,
        source: 'seed',
      },
    ],
    approvedAt: CREATED,
  },
  {
    merchantId: 'bizgram',
    primaryObjective: 'margin',
    secondaryObjective: 'conversion',
    maxDiscountPct: 5,
    minMarginPct: 11,
    bundleAllowance: 45,
    standardWarrantyYears: 2,
    maxWarrantyYears: 3,
    standardDeliveryDays: 1,
    inventoryPriorities: ['high_margin'],
    brandTone: 'Technical and specification-led. Explains why the hardware fits the workload.',
    salesRules: [
      {
        id: 'biz-rule-1',
        kind: 'min_spec_for_workload',
        text: 'Never propose under 16 GB RAM for CAD, ML or engineering workloads.',
        params: { workloads: ['cad', 'engineering', 'ml', 'machine learning'], minRamGb: 16 },
        approved: true,
        source: 'seed',
      },
      {
        id: 'biz-rule-2',
        kind: 'bundle_policy',
        text: 'Standard 2-year warranty is included rather than discounted away.',
        params: {},
        approved: true,
        source: 'seed',
      },
    ],
    approvedAt: CREATED,
  },
  {
    merchantId: 'challenger',
    primaryObjective: 'aov',
    secondaryObjective: 'conversion',
    maxDiscountPct: 3,
    minMarginPct: 9,
    bundleAllowance: 130,
    standardWarrantyYears: 2,
    maxWarrantyYears: 3,
    standardDeliveryDays: 1,
    inventoryPriorities: ['service_attach'],
    brandTone: 'Retail chain. Emphasises service, on-site warranty and next-day delivery.',
    salesRules: [
      {
        id: 'chal-rule-1',
        kind: 'bundle_policy',
        text: 'Attach an accessory or service bundle to every offer where allowance permits.',
        params: {},
        approved: true,
        source: 'seed',
      },
      {
        id: 'chal-rule-2',
        kind: 'never_recommend',
        text: 'Do not offer refurbished units through the agent network.',
        params: { tags: ['refurbished'] },
        approved: true,
        source: 'seed',
      },
    ],
    approvedAt: CREATED,
  },
]
